name: formainz
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tuple: ^2.0.0
  google_sign_in: ^5.0.1
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  cloud_firestore: ^2.1.0
  provider: ^5.0.0
  geolocator: ^7.4.0
  http: ^0.13.3  
  google_maps_flutter: ^2.0.6
  rxdart: ^0.23.1
  flutter_bloc: 
  geocoding: ^2.0.0
  firebase_analytics: ^5.0.2
  firebase_core_web:
  intl:
  file_picker: ^3.0.1
  firebase_storage: ^10.0.2
  font_awesome_flutter: ^8.2.0
  image_picker: ^0.8.3+3
  flutter_svg: ^0.19.1 # help us to use SVG in our app
  flutter_nfc_reader: ^0.1.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_analytics_web: ^0.3.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  
  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/icons/
   - assets/images/
   - assets/
   - assets/marker2.png
   - assets/background.png
   - assets/welcome.png
   - assets/dd.png
   - assets/logos/facebook.jpg
   - assets/logos/google.jpg
   - assets/daniel.png
   - assets/dotthree.png
   - assets/restaurants/starbucks.jpg
   - assets/restaurants/r1.jpg
   - assets/restaurants/r2.jpg
   - assets/restaurants/r3.jpg
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  fonts:
   - family: OpenSans
   
     fonts:
       - asset: assets/fonts/OpenSans.ttf
       - asset: assets/fonts/Avenir-Book.ttf
       - asset: assets/fonts/Avenir-Heavy.ttf
         weight: 700
       - asset: assets/fonts/Avenir-Light.ttf
         weight: 300
       - asset: assets/fonts/Avenir-Medium.ttf
         weight: 500
   - family: Robot
     fonts:
       - asset: assets/fonts/RobotoMono-Medium.ttf
   - family: Poppins
     fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 500

        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 300
   - family: Muli
     fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
